### ISSUE TITLE
mjpg-streamer does not build on armbian

### ISSUE THREAD

**Issue by Freddan-67** [jacksonliam/mjpg-streamer#106]
I downloaded the latest from sourceforge (1c424b5441a2bf8379cdecd7dbebc935 mjpg-streamer-r63.tar.gz).
It does not build on armbian (5.37.180112 for Orange Pi PC+)
A missing struct, a changed define, and libraries after objects.
Suggested patch
`
Makefile
59c59
<       $(CC) $(CFLAGS) $(LFLAGS) $(OBJECTS) -o $(APP_BINARY)
---
>       $(CC) $(CFLAGS) $(OBJECTS) $(LFLAGS) -o $(APP_BINARY)
plugins/input_gspcav1/jconfig.h
25,26c25,26
< #define SPCAGVIDIOPARAM _IOR('v',BASE_VIDIOCPRIVATE + 1,struct video_param)
< #define SPCASVIDIOPARAM _IOW('v',BASE_VIDIOCPRIVATE + 2,struct video_param)
---
> #define SPCAGVIDIOPARAM _IOR('v',BASE_VIDIOC_PRIVATE + 1,struct video_param)
> #define SPCASVIDIOPARAM _IOW('v',BASE_VIDIOC_PRIVATE + 2,struct video_param)
plugins/input_gspcav1/spcav4l.h
37a38
> #include <libv4l1-videodev.h>
78,79c79,80
< #define SPCAGVIDIOPARAM _IOR('v',BASE_VIDIOCPRIVATE + 1,struct video_param)
< #define SPCASVIDIOPARAM _IOW('v',BASE_VIDIOCPRIVATE + 2,struct video_param)
---
> #define SPCAGVIDIOPARAM _IOR('v',BASE_VIDIOC_PRIVATE + 1,struct video_param)
> #define SPCASVIDIOPARAM _IOW('v',BASE_VIDIOC_PRIVATE + 2,struct video_param)
`

**Comment by jacksonliam** [comment]
The sourceforge project is discontinued. 

Have you tried building the code in this repository? Instructions in the README.md 

The formatting of the code section of your comment looks off, try putting it in a code block https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
