### ISSUE TITLE
Device with many inputs

### ISSUE THREAD

**Issue by lcharles123** [jacksonliam/mjpg-streamer#108]
How to specify which input from /dev/video0 should be used?

I have a geovision card with 4 inputs (0 to 3) from analog cams, and i can see the images of the cameras using Motion, but when i start the mjpg-streamer there is no error in terminal, web interface at ?action=stream ,  ?action=stream_0, _1 shows 
404: Not Found!
Invalid input plugin number

Is there an way to enter the input of the device in command line argument?

thanks!

**Comment by jacksonliam** [comment]
Specify multiple `-i` options of input_uvc each one with a different /dev/videoX specified via `-d`.

E.g. `mjpg_streamer -i 'input_uvc.so [options]'`
