### ISSUE TITLE
support for Multiple outputs

### ISSUE THREAD

**Issue by drewcassidy** [jacksonliam/mjpg-streamer#109]
is there any current method for this tool to support multiple outputs, and if not could this be added? for example to stream to both mjpeg (for Octoprint) and to a rtsp stream

**Comment by cms-** [comment]
You should be able to specify multiple -o output plugins.
E.g. mjpg_streamer -o 'output_http.so [options]' -o 'output_rtsp.so [options]'
N.B. the [rtsp plugin](https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/output_rtsp/output_rtsp.c) currently supports only snapshots.

**Comment by drewcassidy** [comment]
oh, good to know. I probably should have just tried it. thanks
