### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by ggbce** [jacksonliam/mjpg-streamer#110]
Hi,

This application is very useful, but almost webcam (or other video source supported) have an audio channel also. It could be very interesting to grab the audio also. I'm not very good with this kind of programming code (A/V streaming), but adding soundtrack capabilities to this application could be give a very good help to put it on first rank of very nice streamers !

**Comment by jacksonliam** [comment]
It's not really possible without using a proper video codec, mjpeg looks like video but it's not really, it's just a bunch of photos sent one after the other.
It solves a lot of problems with buffering and network dropouts and low processing power and is supported by nearly every browser, but is not really proper video. 

You would get into all kinds of audio sync issues etc. And even if I did support something I don't think the receiving end would really know how to play it.

I'd just use a different application along side mjpg-streamer to stream something like mp3 from the microphone and just play both at the receiving end. That's as good as it's going to get with mjpg I'm afraid!
