### ISSUE TITLE
Stereo support in raspicam input plugin

### ISSUE THREAD

**Issue by mminervini** [jacksonliam/mjpg-streamer#115]
I am wandering if the raspicam input plugin supports the stereoscopic mode...

The `-3d` or `--stereo` options are not listed in the help of the plugin, but I had a look at the source code and a `raspicamcontrol_set_stereo_mode()` function appears to be defined in `RaspiCamControl.h`.

Is it just a placeholder for future implementation? Or is it already possible to trigger acquisition in stereo mode?
Thanks!

**Comment by jacksonliam** [comment]
Sorry no plans for that. Its only useful for compute module boards where you can connect two cameras, so a very limited subset. 

RaspiCamControl.h is just copied from raspberry pi git!

If you have two cameras you should be able to run two instances of mjpg-streamer to get both feeds, so can do the 3d stuff on the receiving end. May have to use v4l plugin with raspicam v4l driver for that though!
