### ISSUE TITLE
Dequeuing buffer error

### ISSUE THREAD

**Issue by albydnc** [jacksonliam/mjpg-streamer#116]
I am trying to stream my usb yuv camera from my nanopi m3. I have succeeded with motion but is very slow so I chose this project. 
The error it gives me is:
Libv4l2 error dequeuing buf: timer expired

Ps: in ffmpeg using v4l2src is working totally fine and the same cam on my laptop is streaming with mjpg with no issues.

**Comment by jacksonliam** [comment]
This is an error coming from v4l, something wrong with it releasing the buffers in time. 
Nothing I can really do about it. A newer kernel might help, but I imagine the nanopi is stuck on some specific kernel. 

Are you sure you're using the same capture resolution/framerate/format/quality when using ffmpeg?

Try using different ones with mjpg-streamer, e.g. `-q 50`.
