### ISSUE TITLE
Timestamp overlay feature

### ISSUE THREAD

**Issue by averyjparker** [jacksonliam/mjpg-streamer#119]
I'm thinking this could be a plugin request - it may be that something like this exists and I just can't find it - but how would it be possible to get a timestamp overlayed on the mjpg stream?

**Comment by dvv** [comment]
NB: This will require decompress/compress cycle for every frame, apart from pulling drawing stuff in.

**Comment by jacksonliam** [comment]
Could possibly be done for the raspicam plugin with little impact on performance or using libjepg in input_uvc (more cpu intensive). 

Not a feature I have the need or time to implement (I'd just put a timestamp overlay on the display side...) but would accept pull requests to implement it as an option.
