### ISSUE TITLE
How can I use rstp

### ISSUE THREAD

**Issue by ighack** [jacksonliam/mjpg-streamer#125]
mjpg_streamer -i "input_uvc.so -y" -o "output_rtsp.so -p 8081"
and I via VLC rtsp://pi_of_ip:8081.
I can't see anything
what's solution

PS:
I can see "mjpg_streamer -i "input_uvc.so -y"  -o "output_http.so -w www" " with rtsp://pi_of_ip:8080

**Comment by rhobincu** [comment]
The RTSP plugin is not functional. All it does is expect a filename over UDP and saves a frame from the source as that name. It does not implement the RSTP protocol at all. 

Also, technically RTSP is a control protocol, not a transport one, that means that it is used only to control streaming (play, pause, rewind), not actually transfer video data to the client. That is done using the RTP protocol that is not implemented either in mjpg_streamer.

**Comment by cms-** [comment]
The UDP plugin is nearly identical.

**Comment by jacksonliam** [comment]
Documentation has been update to note functionality.
