### ISSUE TITLE
libv4l2 Message too long

### ISSUE THREAD

**Issue by BytEvil** [jacksonliam/mjpg-streamer#132]
Hi, friends. I have problem with my Logitech C910 webcam.

Debug log is [here](https://pastebin.com/QcfUD5RD).

**Comment by jacksonliam** [comment]
Thanks for the log. Which hardware are you running on and what OS are you using?

**Comment by BytEvil** [comment]
Asus Maximus VI extreme, Archlinux kernel 4.9.96-lts, 046d:0823 Logitech, Inc. (C910) connected to usb 2.0 port.

**Comment by jacksonliam** [comment]
Thanks, most of the references to that message seem to be related to cheap embedded boards with buggy USB implementations or kernel issues, but that shouldn't be the case with your hardware. 

Do you have access to another camera you can test or another system (different hardware/os) just to rule out hardware issues?

**Comment by BytEvil** [comment]
Ok, i'll try to test later with another web camera. I will inform you about my test results. :)
