### ISSUE TITLE
Webcam not working in Octopi

### ISSUE THREAD

**Issue by hybridtracer** [jacksonliam/mjpg-streamer#133]
I posted in octopie issues as well but thought someone here might be able to help as well. I have an old Xbox Vision Webcam that is listed in the known working webcams page.

> https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work

I updated octopi.txt with the listed camera_usb_options after it didn't work out of the box.  This is a fresh image from this morning and updated. Octopi Ver = 0.14.0

> pi@octopi:~/mjpg-streamer $ camera_usb_options="-r VGA -f 10"
pi@octopi:~/mjpg-streamer $ ./mjpg_streamer -i "input_uvc.so $camera_usb_options" -o "output_http.so -w ./www"
MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: 10
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
Unable to set format: 1196444237 res: 640x480
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
pi@octopi:~/mjpg-streamer $

/dev/video0 is there and below is LSUSB Output

> pi@octopi:~/mjpg-streamer $ lsusb
Bus 001 Device 005: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 004: ID 045e:0294 Microsoft Corp.
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Anyone have any idea what I can try to get this fixed and working?

**Comment by hybridtracer** [comment]
There was no other process running and I tried a few of the options including -y. All comes back with same error. I tried more combinations than below and all were the same result.




> pi@octopi:~/mjpg-streamer $ ./mjpg_streamer -i "input_uvc.so $camera_usb_options" -o "output_http.so -w ./www"

        Index       : 0
        Type        : Video Capture
        Pixel Format: 'MJPG' (compressed)
        Name        : Motion-JPEG
                Size: Discrete 160x120
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 176x144
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 320x240
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 352x288
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 960x720
                        Interval: Discrete 0.133s (7.500 fps)

        Index       : 1
        Type        : Video Capture
        Pixel Format: 'YUYV'
        Name        : YUYV 4:2:2
                Size: Discrete 160x120
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 176x144
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 320x240
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 352x288
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                        Interval: Discrete 0.040s (25.000 fps)
                        Interval: Discrete 0.050s (20.000 fps)
                        Interval: Discrete 0.067s (15.000 fps)
                        Interval: Discrete 0.100s (10.000 fps)
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 960x720
                        Interval: Discrete 0.133s (7.500 fps)
                Size: Discrete 1280x960
                        Interval: Discrete 0.133s (7.500 fps)

> pi@octopi:~/mjpg-streamer $ ./mjpg_streamer -i "input_uvc.so $camera_usb_options" -o "output_http.so -w ./www"
MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: 10
 i: Format............: YUYV
 i: JPEG Quality......: 80
 i: TV-Norm...........: DEFAULT
ERROR opening V4L interface: No such file or directory
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed

> pi@octopi:~/mjpg-streamer $ ./mjpg_streamer -i "input_uvc.so $camera_usb_options" -o "output_http.so -w ./www"
MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: 20
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
ERROR opening V4L interface: No such file or directory
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed

**Comment by niko9797** [comment]
I´m getting same problems, but with Orange pi lite with osi webcam.

```
octoprint@orangepilite:~/mjpg-streamer$ sudo mjpg_streamer -i "/usr/local/lib/input_uvc.so -d /dev/video0 -n -y -r 640x480 -f 15" -o "/usr/local/lib/output_http.so -n -w /usr/local/www -p 8080"
MJPG Streamer Version: svn rev: 3:172
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: 15
 i: Format............: YUV
 i: JPEG Quality......: 80
Unable to set format: 1448695129 res: 640x480
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
octoprint@orangepilite:~/mjpg-streamer$ ^C
octoprint@orangepilite:~/mjpg-streamer$ ps -ef | grep mjpg
octopri+  3044  1959  0 01:00 pts/0    00:00:00 grep --color=auto mjpg
octoprint@orangepilite:~/mjpg-streamer$ v4l2-ctl --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
        Index       : 0
        Type        : Video Capture
        Pixel Format: '422P'
        Name        : planar YUV 422
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 1
        Type        : Video Capture
        Pixel Format: 'YU12'
        Name        : planar YUV 420
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 2
        Type        : Video Capture
        Pixel Format: 'YV12'
        Name        : planar YVU 420
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 3
        Type        : Video Capture
        Pixel Format: 'NV16'
        Name        : planar YUV 422 UV combined
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 4
        Type        : Video Capture
        Pixel Format: 'NV12'
        Name        : planar YUV 420 UV combined
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 5
        Type        : Video Capture
        Pixel Format: 'NV61'
        Name        : planar YUV 422 VU combined
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 6
        Type        : Video Capture
        Pixel Format: 'NV21'
        Name        : planar YUV 420 VU combined
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 7
        Type        : Video Capture
        Pixel Format: 'HM12'
        Name        : MB YUV420
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 8
        Type        : Video Capture
        Pixel Format: 'YUYV'
        Name        : YUV422 YUYV
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 9
        Type        : Video Capture
        Pixel Format: 'YVYU'
        Name        : YUV422 YVYU
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 10
        Type        : Video Capture
        Pixel Format: 'UYVY'
        Name        : YUV422 UYVY
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 11
        Type        : Video Capture
        Pixel Format: 'VYUY'
        Name        : YUV422 VYUY
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 12
        Type        : Video Capture
        Pixel Format: 'BA81'
        Name        : RAW Bayer BGGR 8bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 13
        Type        : Video Capture
        Pixel Format: 'GBRG'
        Name        : RAW Bayer GBRG 8bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 14
        Type        : Video Capture
        Pixel Format: 'GRBG'
        Name        : RAW Bayer GRBG 8bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 15
        Type        : Video Capture
        Pixel Format: 'GRBG'
        Name        : RAW Bayer RGGB 8bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 16
        Type        : Video Capture
        Pixel Format: 'BG10'
        Name        : RAW Bayer BGGR 10bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 17
        Type        : Video Capture
        Pixel Format: 'GB10'
        Name        : RAW Bayer GBRG 10bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 18
        Type        : Video Capture
        Pixel Format: 'BA10'
        Name        : RAW Bayer GRBG 10bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 19
        Type        : Video Capture
        Pixel Format: 'BA10'
        Name        : RAW Bayer RGGB 10bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 20
        Type        : Video Capture
        Pixel Format: 'BG12'
        Name        : RAW Bayer BGGR 12bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 21
        Type        : Video Capture
        Pixel Format: 'GB12'
        Name        : RAW Bayer GBRG 12bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 22
        Type        : Video Capture
        Pixel Format: 'BA12'
        Name        : RAW Bayer GRBG 12bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

        Index       : 23
        Type        : Video Capture
        Pixel Format: 'BA12'
        Name        : RAW Bayer RGGB 12bit
                Size: Discrete 1600x1200
                Size: Discrete 1280x720
                Size: Discrete 640x480

```

**Comment by taratata2016** [comment]
i have the same prob with SQ-11!

i try with Havic HV-N5086 and work fine.

i continue to find solution

**Comment by jacksonliam** [comment]
Closing as camera specific issues, and a few different ones mixed in here.
