### ISSUE TITLE
Start automatic with OctoPrint

### ISSUE THREAD

**Issue by taratata2016** [jacksonliam/mjpg-streamer#154]
Hi,

how to setting mjpg-streamer-experimental for start in auto mode with OctoPrint type source?

now i use the manual way
cd mjpg-streamer/mjpg-streamer-experimental
./mjpg_streamer -i "./input_uvc.so" -o "./output_http.so"

and see the cam on otocprint.

Thank you 
Have good day

**Comment by jacksonliam** [comment]
Not an mjpg-streamer issue
