### ISSUE TITLE
output_http from mjpeg source

### ISSUE THREAD

**Issue by rusttree** [jacksonliam/mjpg-streamer#165]
I have an embedded device that has hardware support for encoding mjpeg files using a native gsteamer plugin. So I can generate an mjpeg file directly from gstreamer. I would like to use mjpg-streamer to view the file from a web browser using the output_http plugin.

Is it possible for mjpg-streamer to directly consume an mjpeg file and use the output_http plugin so I can view it from a web browser?

**Comment by jacksonliam** [comment]
There is input_file but it expects to see individual jpeg files appear, one for each frame. I guess you could use a folder in /tmp and get gstreamer to output there? Or I believe gstreamer can output HTTP.
