### ISSUE TITLE
Camera control

### ISSUE THREAD

**Issue by m5x** [jacksonliam/mjpg-streamer#171]
Is real-time camera control (control.htm) supposed to work with input_raspicam.so? With latest source it does not work for me. HTTP output plugin returns following program.json:

```
{
"inputs":[
{
"id": "0",
"name": "(null)",
"plugin": "input_raspicam.so",
"args": " -x 2592 -y 1944 -fps 15 -quality 95"
}
],
"outputs":[
{
"id": "0",
"name": "HTTP output plugin",
"plugin": "output_http.so",
"args": " -w ./www"
}
]}
```

That might be ok except the "(null)" value for raspicam input plugin name. However this is input0.json and output0.json respectivelly:

```
{
"controls": [

],
"formats": [

]
}
```

```
{
"controls": [

]
}
```

Both are empty, I'd expect many controls at least for the input plugin. I am using OctoPi release 0.15.1 on RPi 3. I tried both the version distributed with OctoPi as well as custom build version from latest sources - both behave the same in this regard. From looking at the source code it looks like camera control for raspicam is implemented but for some reason it is not working for me. What can I be doing wrong?

**Comment by jacksonliam** [comment]
Nope this is not supported by input_raspicam

Might have some luck loading the official raspicam v4l2 driver and using input_uvc (with slightly worse performance)
