### ISSUE TITLE
webcam doesn't work

### ISSUE THREAD

**Issue by vincent8535** [jacksonliam/mjpg-streamer#180]
i use a camaera sq11 on my linkit 7688 and trying to use mjpg+streamer but it keeps come out error
 
root@mylinkit:~# mjpg_streamer -i "input_uvc.so -d /dev/video0 -r 1280x720 -f 30" -o "ouput_http.so -p 8080 -w /www/webcam"
MJPG Streamer Version: svn rev: exported
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 1280 x 720
 i: Frames Per Second.: 30
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
Unable to set format: 1196444237 res: 1280x720
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed

and i check my camera format and shows out 
root@mylinkit:~# v4l2-ctl --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
        Index       : 0
        Type        : Video Capture
        Pixel Format: 'MJPG' (compressed)
        Name        : MJPEG
                Size: Discrete 1280x720
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
                        Interval: Stepwise 0.033s - 0.033s with step 0.000s (30.000-30.000 fps)
and keep running.
plase help

**Comment by jacksonliam** [comment]
Looks like you're using an old version, can you try the latest code?

**Comment by vincent8535** [comment]
i try update the version and it show up 
root@mylinkit:~# opkg install kmod-video-uvc mjpg-streamer
Package kmod-video-uvc (3.18.21-1) installed in root is up to date.
Package mjpg-streamer (r182-7) installed in root is up to date.
and still won't work

**Comment by jacksonliam** [comment]
opkg is installing an older version. I don't maintain the packages installed by distros and don't know who does.

Install it from the source in this repo to get the latest code.

**Comment by jacksonliam** [comment]
Search google for a suitable blog, there are lots of them.

**Comment by vincent8535** [comment]
i try to use my cam on ubuntu and show out 
vincents@vincents-VirtualBox:/dev$ mjpg_streamer -i "input_uvc.so -d /dev/video0 -r 1280x720 -f 30" -o "output_http.so -p 8080 -2/www/webcam"
MJPG Streamer Version: git rev: ddb69b7b4f114f3c2ca01adf55712792ca8aed43
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 1280 x 720
 i: Frames Per Second.: 30
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
Unable to set format: 1196444237 res: 1280x720
Init v4L2 failed !! exit fatal
 i: init_VideoIn failed

**Comment by jacksonliam** [comment]
Hmmm probably an issue with the cam or its driver. Do other mjpg capture apps work? e.g.ffmpeg? `ffmpeg -f v4l2 -input_format mjpeg -i /dev/video0 -c:v copy output.mkv`
