### ISSUE TITLE
View multiple inputs on HTTP stream

### ISSUE THREAD

**Issue by iDoObject** [jacksonliam/mjpg-streamer#186]
I'm trying to get this set up, and I'm having trouble getting `output_http.so` to play multiple inputs. The camera lights turn on indicating that they're in use but I can't figure out how to see their streams - I can only see the stream of the first input.

Here's the command I'm using:
```
$ mjpg_streamer -o "output_http.so -w ./www" -i "input_uvc.so -d /dev/video0" -i "input_uvc.so -d /dev/video1" -i "input_raspicam.so"
```

In this example, I can only see `/dev/video0` and not `/dev/video1` or the Rasberry Pi camera.

**Comment by jacksonliam** [comment]
The output http readme has info on accessing streams of multiple plugins

https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/output_http/README.md

e.g.
```
http://127.0.0.1:8080/?action=stream_0
http://127.0.0.1:8080/?action=stream_1
```
