### ISSUE TITLE
"Bufferize" output

### ISSUE THREAD

**Issue by base64encrypted** [jacksonliam/mjpg-streamer#201]
Hello,

I'm trying to synchronize mjpg-streamer with darkice. With darkice, i can not get a buffer less than three seconds, which it creates an offset with mjpg-streamer.

Do you known how to reduce the lag between the two softs by buffering the output of mjpg-streamer three seconds ?

Thx.

**Comment by jacksonliam** [comment]
Not without significant code changes, there is a double buffer but that's it. Perhaps whatever is receiving the streams could buffer it?
