### ISSUE TITLE
ERROR: could not find input plugin

### ISSUE THREAD

**Issue by huazai665** [jacksonliam/mjpg-streamer#207]
ERROR: could not find input plugin
       Perhaps you want to adjust the search path with:
       # export LD_LIBRARY_PATH=/path/to/plugin/folder
       dlopen: ./input_raspicam.so: cannot open shared object file: No such file or directory

**Comment by jacksonliam** [comment]
What commands did you run?

**Comment by huazai665** [comment]
./mjpg_streamer -i "./input_raspicam.so" -o "./output_http.so -w ./www"

**Comment by jacksonliam** [comment]
And did you first run
`export LD_LIBRARY_PATH=.`
?

**Comment by huazai665** [comment]
![image](https://user-images.githubusercontent.com/32571541/57179001-638a9400-6eab-11e9-86dc-65e6c740260b.png)
yes

**Comment by jacksonliam** [comment]
It's probably not getting built, I assume you're building on a raspberry pi? Which OS did you build it on? 

When you build in the console output under the section 
`-- The following features have been disabled:`

Does it list 
 `* PLUGIN_INPUT_RASPICAM , Raspberry Pi input camera plugin (unmet dependencies)`
?

**Comment by huazai665** [comment]
I have built it on raspberry 3B+ successfully and the OS is ubuntu mate 18.02.
![image](https://user-images.githubusercontent.com/32571541/57179441-9a16dd80-6eb0-11e9-8e4f-7ef52e45df1c.png)

**Comment by jacksonliam** [comment]
Did you figure this out? I just noticed the argument should be "input_raspicam.so"  not "./input_raspicam.so".
