### ISSUE TITLE
Force Format MJPEG, not JPEG?

### ISSUE THREAD

**Issue by Nappyy** [jacksonliam/mjpg-streamer#210]
Hi There, 

if I try to make a stream from my webcam it always uses "Format............: JPEG", not "MJPEG.

"v4l2-ctl --list-formats" output returns:
> ioctl: VIDIOC_ENUM_FMT
>         Index       : 0
>         Type        : Video Capture
>         Pixel Format: 'MJPG' (compressed)
>         Name        : Motion-JPEG
> 
>         Index       : 1
>         Type        : Video Capture
>         Pixel Format: 'YUYV'
>         Name        : YUYV 4:2:2
> 

Full output on mjpg-steamer start:
 ./mjpg_streamer -o "output_http.so -p 8090 -w ./www" -i "input_uvc.so"

> MJPG Streamer Version.: 2.0
>  i: Using V4L2 device.: /dev/video0
>  i: Desired Resolution: 640 x 480
>  i: Frames Per Second.: -1
>  i: Format............: JPEG
>  i: TV-Norm...........: DEFAULT
> UVCIOC_CTRL_ADD - Error at Pan (relative): Inappropriate ioctl for device (25)
> UVCIOC_CTRL_ADD - Error at Tilt (relative): Inappropriate ioctl for device (25)
> UVCIOC_CTRL_ADD - Error at Pan Reset: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_ADD - Error at Tilt Reset: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_ADD - Error at Pan/tilt Reset: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_ADD - Error at Focus (absolute): Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at Pan (relative): Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at Tilt (relative): Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at Pan Reset: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at Tilt Reset: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at Pan/tilt Reset: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at Focus (absolute): Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at LED1 Mode: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at LED1 Frequency: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at Disable video processing: Inappropriate ioctl for device (25)
> UVCIOC_CTRL_MAP - Error at Raw bits per pixel: Inappropriate ioctl for device (25)
>  o: www-folder-path......: ./www/
>  o: HTTP TCP port........: 8090
>  o: HTTP Listen Address..: (null)
>  o: username:password....: disabled
>  o: commands.............: enabled

Using this, the server causes high CPU usage...

Can anyone tell me, how to use MJPEG instead of JPEG stream format?

Kind regards
Kai

**Comment by jacksonliam** [comment]
They're the same thing as far as mjpg-streamer is concerned. I think that just lists what was asked for not what the camera returned anyway.

The only thing that should be causing high CPU is if you use the -y flag.
