### ISSUE TITLE
Streamer flakiness

### ISSUE THREAD

**Issue by PeterGhimself** [jacksonliam/mjpg-streamer#212]
I have been using mjpg-streamer for a little while now and have encountered some flakiness that I simply cannot trace or consistently reproduce. Normally I will start the stream and it will be running properly since when I visit `https://localhost:8090/?action=stream` in chrome it _does_ show me the video stream, however every now and then I just see a black screen (sometimes it shows me one frame very quickly and then goes black). I'll try to give as much context as I can, but unfortunately I never get any errors/warnings in the output so it's very unclear to me what is actually causing this issue.

I run the code by placing it into a bash script and calling that:
```
#!/usr/bin/env bash

# since this command usually requires to be run as sudo
# this file was changed to be owned by root so it can be called
# from other scripts without needing to run the initial script as sudo
# this was achieved with `sudo chown root:root start_stream.sh`

DEVICES="$(v4l2-ctl --list-devices)"

echo "$DEVICES" > tmp


if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    port=`tail -1 tmp`
    port="$(echo -e "${port}" | sed -e 's/^[[:space:]]*//')"
    echo "port: $port"
  else
    echo "Port argument supplied: $1"
    port=$1
fi

# for inspiron 15 7000 gaming laptop built in webcam resolution: 1280/720 (848/480 works too), for our c920 cameras: 640/480
/usr/local/bin/mjpg_streamer  -i "input_uvc.so -r 640x480 -m 50000 -n -f 1 -d $port" -o "output_http.so -p 8090 -w /usr/local/share/mjpg-streamer/www/"

# to install dependencies:
# $ git clone https://github.com/jacksonliam/mjpg-streamer.git
# $ cd mjpg-streamer/mjpg-streamer-experimental
# $ sudo apt-get install cmake libjpeg62-dev
# $ make
# $ sudo make install

# NOTE: using mjpeg streams limits us to capturing them using more limited img tags
# instead of the newer video tags
```

And the output is normal, as usual:

```
MJPG Streamer Version: git rev: 501f6362c5afddcfb41055f97ae484252c85c912
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: 1
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
 i: The specified resolution is unavailable, using: width 848 height 480 instead 
 i: FPS coerced ......: from 1 to 30
 o: www-folder-path......: /usr/local/share/mjpg-streamer/www/
 o: HTTP TCP port........: 8090
 o: HTTP Listen Address..: (null)
 o: username:password....: disabled
 o: commands.............: enabled
```

I have tried setting the resolution to 848x480 in the script, rebooting the computer: both of these attempts did not seem to actually help the situation. I got frustrated and left my laptop alone for about 10-15 minutes, came back, tested it again and it works. I have seen this problem appear in the past using usb cameras (instead of my laptops built in webcam, most recently). The most recent testing was done locally but I have seen this problem appear when using multiple machines as well.

Additionally: The resolution and frame rate are set this low because in the project I'm working on we are using the odroid xu4 to turn the stream ON/OFF on request. We suspect the encoding of the video stream at higher rates is the cause for extreme stress on the odroid. If I set the frame rate/resolution higher than the values in the script and request a video stream and then request to turn it off it takes about 30 seconds  for the odroid to actually register the request and kill the process (tested by issuing commands from a laptop using an ethernet cable to connect to the odroid). I'm using ubuntu 16.04 in any case.

**Comment by jacksonliam** [comment]
I think you are running at 30fps anyway, because your camera doesn't support a lower frame rate at the requested resolution. You can drop more frames using the softfps option, which might help your problem.

Is the static image url black too? If so could you upload one?

I'm not sure if this could be a mjpg streamer fault, I'm thinking it would be an OS / driver / hardware thing.
