### ISSUE TITLE
Package 'libjpeg8-dev' has no installation candidate

### ISSUE THREAD

**Issue by schneemaier** [jacksonliam/mjpg-streamer#222]
Following the instructions for building the package i got error preparing the environment:

apt-get install cmake libjpeg8-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libjpeg8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg62-turbo-dev

E: Package 'libjpeg8-dev' has no installation candidate

Linux version: debian Strech arm

apt install libjpeg62-turbo-dev seems to fix the problem

**Comment by janeoa** [comment]
Same

**Comment by Cyan101** [comment]
still an issue
