### ISSUE TITLE
change roi while streaming?

### ISSUE THREAD

**Issue by mark-hahn** [jacksonliam/mjpg-streamer#225]
Is there some way to change ROI while streaming?  I don't care if I use raspicam or uvc.

ROI only seems to be available on raspicam and only uvc can change params while streaming.  Is this correct?

If it can't be changed on the fly is there a relatively seamless way to stop/restart streaming to achieve something similar?

**Comment by jacksonliam** [comment]
In theory it should be possible to implement controls for the raspi plugin, it would just quickly restart the MMAL pipeline with the new params without closing the stream.

However it's not something I've ever found a need for so is unlikely to be something I will implement myself.

I suggest adding logic in the client to crop the stream or to automatically restart it after mjpg-streamer is restarted with the new params.
