### ISSUE TITLE
how to get good image in both day and night continuous use

### ISSUE THREAD

**Issue by Maximize0987** [jacksonliam/mjpg-streamer#230]
Hello.  I am trying to get my setup to get a good image in both day and night.  without any special arguments I get good if not great picture under a carport roof in the daytime.  Later in the middle of dusk the image gets too dark and is unusable.  I have found that adding -br 65, and -wb 2 gets a better balance but at the cost of a somewhat washed out daytime image.

I am using a pi zero w with pi noir camera
![IMG_0520 1](https://user-images.githubusercontent.com/42393700/68551744-55bf4980-03cd-11ea-9fad-bde8cdc0aa91.JPG)
![IMG_0521 1](https://user-images.githubusercontent.com/42393700/68551750-6e2f6400-03cd-11ea-8590-f4c1b8ec5082.PNG)
![IMG_0522 1](https://user-images.githubusercontent.com/42393700/68551784-90c17d00-03cd-11ea-911a-08c8e5538d5a.PNG)
![IMG_0524 1](https://user-images.githubusercontent.com/42393700/68551866-3aa10980-03ce-11ea-8c4d-e50eded140f1.JPG)

these pictures are taken at 3pm, first with the arguments, second without the the third with a iphonex
we are facing east with the sun at 4:30/5 o'clock

**Comment by jacksonliam** [comment]
Hmmm not sure, are there not any auto exposure modes / flags you can try? Have you tried the usestills flag? It's max 8 fps frame rate but might work better for the changing lighting.

This is more of a camera issue than mjpg-streamer one though. Unless there are any flags in raspivid which help and mjpg-streamer doesnt have?
