### ISSUE TITLE
How to set bitrate value

### ISSUE THREAD

**Issue by arcfidalgo** [jacksonliam/mjpg-streamer#237]
Hi, 

I would like to develop an application that capture video for usb camera and send them. But on sending  the video stream to the receiver I have an limited bandwith, 96kps, this is my main issue. The other is get low latency. Theres no problem if video quality is a bit lower. 
My question is if exist any way to set the bitrate to this value.
Thanks for the attention

**Comment by jacksonliam** [comment]
No but the frames will be dropped to take the available bandwidth, the client always gets the latest frame when it requests one.

If you need to limit the bandwidth I think that's something you could do in Linux.

**Comment by JooJooBee666** [comment]
Just something I found out that may help here.  You can use a value higher than 100 on the JPEG quality.  For example, I found that if I'm streaming a 1600x1200 video setting the quality to 300 gets me a better quality video.  100 at that resolution produces nothing but ugly blocks.  For example, to stream to a web server with the first video V4L2 device, use the following:

`./mjpg_streamer -o output_http.so -w ./www-root-n --listen 127.0.0.1 -i input_uvc.so -r 1600x1200 -f 15 -q 300 -d /dev/video0`

Hope this helps someone else running in to this issue as well.  This was the only way I could find to increase the quality for higher resolution streams.  If anyone has a better way, do tell!
