### ISSUE TITLE
error when running make

### ISSUE THREAD

**Issue by CastillloFrancisco2018** [jacksonliam/mjpg-streamer#244]
i got:
[ -d _build ] || mkdir _build
[ -f _build/Makefile ] || (cd _build && cmake  -DCMAKE_BUILD_TYPE=Release ..)
/bin/sh: 1: cmake: not found
make: *** [Makefile:18: all] Error 127

after just running make in the experimental file

**Comment by jacksonliam** [comment]
sudo apt-get install cmake
