### ISSUE TITLE
change webcam source?

### ISSUE THREAD

**Issue by XxTWMLxX** [jacksonliam/mjpg-streamer#245]
How can i change the webcam mjpg-streamer is using? 

its defaulting to my laptops internal, when i want to use this laptop for a octoprint server, so i have a usb webcam that i want to use.

xubuntu on my laptop is picking up both cameras though:
crw-rw----+ 1 root video 81, 0 Apr 18 06:04 /dev/video0
crw-rw----+ 1 root video 81, 1 Apr 18 06:41 /dev/video1

but streamer is only using the default video0 internal camera.

**Comment by jacksonliam** [comment]
-d /dev/video1

**Comment by XxTWMLxX** [comment]
Where do I put that? In what config file?
or how do I run it as a command?
