### ISSUE TITLE
Arducam Motorized Focus Camera support

### ISSUE THREAD

**Issue by evandene** [jacksonliam/mjpg-streamer#269]
I'm in the process designing a sort of endoscope with a raspberry pi camera build in and all works really nice, thanks for the great job done already.
Question: Is there any option thinkable for making the Arducam camera with Motorized focus to work with mjpg-streamer?
The Arducam 5MP camera with Motorized Focus (Sensor OV5647) works great when I run them standalone on my Raspberry pi Zero W, but when starting up the mjpg-streamer, the auto focus doesn't work, I just get a fix focus stream.

The Github link to the Arducam/Raspberry pi support site is: https://github.com/ArduCAM/RaspberryPi/tree/master/Motorized_Focus_Camera

Any help is welcome
Best regards, Ed

**Comment by jacksonliam** [comment]
So it looks like the camera is just motorized, with the autofocus actually done by analysing the images on the Pi, moving the camera by executing i2c commands? The examples in the git repo seem to use a python script to do this.

If you can get it to work, as it's quite specific about the versions of things, we have an OpenCV plugin with Python support.  You could probably get that autofocus python code from that git repo to run inside that. Have a read of the documentation for it (links in the Readme.md)

What the performance will be like on a pi zero I have no idea.
