### ISSUE TITLE
Error during higher resolution captures with Pi HQ camera

### ISSUE THREAD

**Issue by dustinkerstein** [jacksonliam/mjpg-streamer#273]
I am able to capture in both the default and usestills mode at around 2400x2000, but going much higher (or to native resolution of the sensor) throws this error:

```
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
camera couldn't be enabled
```

Has anyone else seen this? This is on a fresh raspbian install and latest updates. Thanks!

**Comment by dustinkerstein** [comment]
FYI, the last working size is 2944x2049. Anything higher for X or Y will throw the above error.

**Comment by dustinkerstein** [comment]
This was fixed by upping the Pi's GPU memory limit.

**Comment by jacksonliam** [comment]
Thanks for posting the fix!

**Comment by thetruejay7002** [comment]
I tried upping the gpu mem but it didn’t work
