### ISSUE TITLE
"CAMERA_OPTION" variable.

### ISSUE THREAD

**Issue by TNT911** [jacksonliam/mjpg-streamer#277]
within mjpg-streamer.init
`       --umask $UMASK -- -i "${INPUT_UVC_LIB} ${CAMERA_USB_OPTIONS}" -o "${OUTPUT_HTTP_LIB} -w ${WWW_ROOT}"`
should be
`       --umask $UMASK -- -i "${INPUT_UVC_LIB} ${CAMERA_OPTIONS}" -o "${OUTPUT_HTTP_LIB} -w ${WWW_ROOT}"`
to match mjpg-streamer.default
no?

**Comment by jacksonliam** [comment]
Yes possibly,
cc @cmumford as they added these. This seem right to you? We going to break anything with these changes?

**Comment by cmumford** [comment]
Yes, I agree with the change to `${CAMERA_OPTIONS}`. I tried to figure out why ever used `${CAMERA_USB_OPTIONS}`, but I couldn't. Nice catch.
