### ISSUE TITLE
Does not work UVC camera with H264

### ISSUE THREAD

**Issue by md-rubel** [jacksonliam/mjpg-streamer#290]
pi@raspberrypi:~ /mjpg-streamer-1.0.0/mjpg-streamer-experimental $ lsusb
Bus 001 Device 003: ID 040d:300a VIA Technologies, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
pi@raspberrypi:~ /mjpg-streamer-1.0.0/mjpg-streamer-experimental $ v4l2-ctl --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'H264' (H.264, compressed)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 2048x1024
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
pi@raspberrypi:~ /mjpg-streamer-1.0.0/mjpg-streamer-experimental $ ./mjpg_streamer -i "input_uvc.so -d /dev/video0 -" -o "output_http.so -w ./www"
MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: -1
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
 i: Could not obtain the requested pixelformat: MJPG , driver gave us: H264
    ... will try to handle this by checking against supported formats. 
Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
pi@raspberrypi:~ /mjpg-streamer-1.0.0/mjpg-streamer-experimental $ 

![image](https://user-images.githubusercontent.com/20143129/106328415-fd15ee00-62a9-11eb-9c86-1528c81fd5b4.png)

**Comment by jacksonliam** [comment]
Yes h264 would not be supported as we would need to decode it.

mjpg-streamer only works with cameras that supply mjpg, or one of the raw formats that's easily encoded to jpeg like yuv or RGB.
