### ISSUE TITLE
Unable to map buffer: Invalid argument

### ISSUE THREAD

**Issue by pputnik** [jacksonliam/mjpg-streamer#291]
Hello,

Thank you for the project, it works really well! I have no problem with more-or-less new webcam but the older one fails, could you help, please? 
USB cam: "Genius VideoCAM Eye"
```
 v4l2-ctl --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'S910' (GSPCA SN9C10X, compressed)
                Size: Discrete 160x120
                Size: Discrete 176x144
                Size: Discrete 320x240
                Size: Discrete 352x288
        [1]: 'BA81' (8-bit Bayer BGBG/GRGR)
                Size: Discrete 160x120
                Size: Discrete 176x144
```
the command:
`mjpg_streamer -i "input_uvc.so -d /dev/video0 -r 320x240 -fourcc RGB24" -o "output_http.so -p 8090 -w /usr/local/share/mjpg-streamer/www"`

The output: 
```
MJPG Streamer Version: git rev: 5554f42c352ecfa7edaec6fc51e507afce605a34
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 320 x 240
 i: Frames Per Second.: -1
 i: Format............: RGB24
 i: JPEG Quality......: 80
 i: TV-Norm...........: DEFAULT
Unable to map buffer: Invalid argument
Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
```
I tried to play with framerate, `-u -fourcc RGB2P`, just  `-u`, without `-fourcc RGB24` but it idin't help. What should I do with that?

Could you advise, please? Thank you.

**Comment by jacksonliam** [comment]
Unfortunately that camera doesn't support mjpg or any format that can easily be converted to it (YUV, RGB).

It seems to support raw bayer capture. Maybe someone could implement something like https://github.com/UbiCastTeam/gst-plugins-elphel/blob/master/bayer2rgb2/src/gstbayer2rgb2.c
But I doubt it would be worth the effort.
