### ISSUE TITLE
Multiple output

### ISSUE THREAD

**Issue by gerben-b** [jacksonliam/mjpg-streamer#293]
Thanks for this wonderful piece of software. I really enjoy using it.

I tried to configure an output to web and an output to file simultaneously but that did not work. Is it possible to use mjpg_streamer that way?

**Comment by jacksonliam** [comment]
Should work, what command did you run?

**Comment by gerben-b** [comment]
I got it working now, must have done something stupid. I just specified another -o "something" and that worked fine.

Thanks :-)
