### ISSUE TITLE
Problem with webcam 

### ISSUE THREAD

**Issue by miko671995** [jacksonliam/mjpg-streamer#304]
Hello. I have a problem with streaming on my orange pi pc. i use the lastest armbian system. 

there is my first problem - 

`root@orangepipc:/tmp/mjpg-streamer/mjpg-streamer-experimental#  ./mjpg_streamer -i "input_uvc.so  -d /dev/video1" -o "output_http.so"
MJPG Streamer Version: git rev: 310b29f4a94c46652b20c4b7b6e5cf24e532af39
 i: Using V4L2 device.: /dev/video1
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: -1
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
 i: Could not obtain the requested pixelformat: MJPG , driver gave us: RGB3
    ... will try to handle this by checking against supported formats.
    ... Falling back to RGB24 mode (consider using -fourcc RGB24 option). Note that this requires much more CPU power
Unable to map buffer: Invalid argument
Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
`

after trying adding -fourcc RGB 

`root@orangepipc:/tmp/mjpg-streamer/mjpg-streamer-experimental# ./mjpg_streamer -i "input_uvc.so -fourcc RGB24 -d /dev/video1" -o "output_http.so"
MJPG Streamer Version: git rev: 310b29f4a94c46652b20c4b7b6e5cf24e532af39
 i: Using V4L2 device.: /dev/video1
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: -1
 i: Format............: RGB24
 i: JPEG Quality......: 80
 i: TV-Norm...........: DEFAULT
Unable to map buffer: Invalid argument
Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
`
`root@orangepipc:/tmp/mjpg-streamer/mjpg-streamer-experimental# lsusb
Bus 008 Device 002: ID 093a:2625 Pixart Imaging, Inc.

**Comment by jacksonliam** [comment]
What's the output of `v4l2-ctl --list-formats-ext`?

**Comment by miko671995** [comment]
root@orangepipc:/tmp/mjpg-streamer/mjpg-streamer-experimental# v4l2-ctl --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'ST12' (Sunxi Tiled NV12 Format, compressed)
        [1]: 'NV12' (Y/CbCr 4:2:0)

**Comment by jacksonliam** [comment]
Yeah that camera is not going to work

**Comment by tneijsel** [comment]
This camera works fine wit Webcamoid  on Desktop on XFCE on Orange pi Pc Plus running:

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Armbian 22.11.4 Focal"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

But I am unable to get it working. The purpose is to get the usb webcam image streaming in Octoprint which is installad and running.
in Motion the video I get unable to decode video.. 

V4l2 output:
v4l2-ctl --list devices
cedrus (platform:cedrus):
	/dev/video0
	/dev/media0

USB PHY 2.0: USB CAMERA (usb-1c1b000.usb-1):
	/dev/video1
	/dev/video2
	/dev/media1

And on format:
v4l2-ctl --list-formats
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'ST12' (Sunxi Tiled NV12 Format, compressed)
	[1]: 'NV12' (Y/CbCr 4:2:0)

So if the webcamoid application is running the camera on esktop by default is it not possible to get any image in Motion or any other program I tested. 

Help Appreciated.
Ton.
