### ISSUE TITLE
date and time wrong in the stream timestamp

### ISSUE THREAD

**Issue by anzbert** [jacksonliam/mjpg-streamer#314]
I am using this great tool to stream from a raspberry pi zero W with a usb webcam. i am using the input_uvc.so plugin and the output_http.so. Everything works fantastic, except I have no control over the on-stream timestamp, which is also showing the wrong time.
The linux date has been set correctly and the date function is showing the right time in the terminal.
I am unsure what I can do and if it is a UVC driver issue or a MJPG problem.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/38823700/128168695-cd370556-d137-433d-b043-991c9e83c102.png">

Thanks for the help!
Andreas

**Comment by anzbert** [comment]
these are my startup settings:
mjpg_streamer -i "input_uvc.so --no_dynctrl -r 1280x720" -o "output_http.so -p 8080"

**Comment by jacksonliam** [comment]
This is not added by mjpg-streamer so must be the camera or output device.
