### ISSUE TITLE
stream in YUV format

### ISSUE THREAD

**Issue by milahu** [jacksonliam/mjpg-streamer#323]
why not simply stream in YUV format, when the camera does not support MJPG?

```
 i: Could not obtain the requested pixelformat: MJPG , driver gave us: YUYV
    ... will try to handle this by checking against supported formats. 
    ... Falling back to YUV mode (consider using -yuv option). Note that this requires much more CPU power
```

i am aware that YUV is uncompressed, but in my case, i only need like 1 FPS

maybe there is a cheap way to scale the YUV image to 50% or 25% (skip every second pixel)

related #58 

could be prototyped with https://github.com/pupil-labs/pyuvc

**Comment by jacksonliam** [comment]
I don't think mjpg-streamer is the right tool for that. It's written to expect all input and output plugins to deal with jpeg frames. It would be a lot of work to make it be able to deal with multiple types of frame.

I wanted to add h264 but decided it would be better to just start from scratch. 

This is also a fairly specific application which most people wouldn't find useful.

You could probably use python libraries to make a v4l2 yuv frame streamer fairly quickly.
