### ISSUE TITLE
Rasbian Bullseye

### ISSUE THREAD

**Issue by Phaiax** [jacksonliam/mjpg-streamer#324]
Hi.

I failed to get mjpg-streamer running after an upgrade to rasbian bullseye. Only then I found [this information](https://www.raspberrypi.com/documentation/accessories/camera.html)  :

> Raspberry  Pi is transitioning from a legacy camera software stack based on  proprietary Broadcom GPU code to an open-source stack based on libcamera. Raspberry Pi OS images from Bullseye onwards will contain only the libcamera-based stack. Raspberry Pi OS images up to and including Buster will contain the legacy Raspicam stack, though the libcamera stack and applications can be built by following the normal build instructions.

Also all the videocore tools don't live in `/opt/vc` anymore. They are integrated into the `/usr` structure.

Maybe this info should be added to the readme? I'll try to find an alternative and post an update here afterwards.

Phaiax

**Comment by jacksonliam** [comment]
Yes it's probably time to deprecate the input raspicam plugin, the raspicam can be used via v4l2 and the uvc plugin now anyway. This mjpg-streamer repo is probably still the best one for most people because it's had a fair few tweaks and patches to the uvc plugin. 

The raspicam plugin should automatically not be built if the headers are lacking. So hopefully we do not need to do anything for mjpg-streamer to run on Bullseye.

**Comment by jacksonliam** [comment]
Maybe we need a libcamera plugin... But tbh I think mjpg-streamer only really has legacy use now. Most browsers support streaming h264 or even AV1 now which has clear advantages. 

So I'd probably want to work on a project to stream those instead.

**Comment by jacksonliam** [comment]
To clarify, switch to using the input_uvc plugin with the raspicam v4l2 driver on Bullseye and things should 'just work'.

**Comment by BeebBenjamin** [comment]
Just commenting here for other people's benefit.  You can disable the new libcamera stack and re-enable the V4L2 driver by following the instructions here: https://forums.raspberrypi.com/viewtopic.php?p=1935591&sid=b0c61887cb4c3352cae9596e9fb6bb88#p1935591

Then you can run mjpg-streamer with the following command:
```bash
export LD_LIBRARY_PATH=. | ./mjpg_streamer -o "output_http.so -w ./www" -i "input_uvc.so"
```
