### ISSUE TITLE
pausing input when output is unused

### ISSUE THREAD

**Issue by d-a-v** [jacksonliam/mjpg-streamer#345]
I would like to know if the API allows to inform the input that the output is idle.

For example the http output can be idle when no web client is connected.
Specific input device could be in rest mode in this case. I am thinking of a thermal camera.

Thanks for any help

**Comment by jacksonliam** [comment]
Sorry no this is not supported. The inputs just fill a buffer and the outputs read from it. It would need a bit of a rework to the plugins API to support this use case.
