### ISSUE TITLE
make a stream of a dir using M-jpeg

### ISSUE THREAD

**Issue by HelderVSousa** [jacksonliam/mjpg-streamer#35]
Well the idea  is simple,  make a stream based in images jpeg for devices as digital frame, or ip-Tv.
The idea is to have folder XPTO that have a live stream and when we put photos or images into folder they will be automatically sent for stream.

**Comment by jacksonliam** [comment]
You should be able to use the input_file plugin to do this 
-i "input_file.so -f /tmp/stream
