### ISSUE TITLE
Lowest framerate is 2 fps

### ISSUE THREAD

**Issue by tobiasschuerg** [jacksonliam/mjpg-streamer#357]
As not many fps are needed I'd like to put this rather low to save computing power for other things.

However, `2` fps is the lowest I can set.

With `1` fps the stream is just black.

Setting something lower `1` (0.5) gets cast to `0`, not limiting the framerate at all.

**Comment by jacksonliam** [comment]
If 1fps is black that's probably a problem with your camera driver. Most cameras have minimum of around 15fps usually. 

If you're using input uvc you can use the every frame option to drop frames.

 [-e | --every_frame ]..: drop all frames except numbered
