### ISSUE TITLE
E: Package 'libjpeg8-dev' has no installation candidate

### ISSUE THREAD

**Issue by kobzzon** [jacksonliam/mjpg-streamer#373]
klipper@armbian:~$ sudo apt-get install cmake libjpeg8-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libjpeg8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg62-turbo-dev:armhf libjpeg62-turbo-dev

E: Package 'libjpeg8-dev' has no installation candidate
klipper@armbian:~$ sudo apt-get install gcc g++
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
g++ is already the newest version (4:10.2.1-1).
gcc is already the newest version (4:10.2.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
![turbo](https://user-images.githubusercontent.com/95584234/204587406-92c16772-0b50-438d-a76c-dd79600eb41e.jpg)

**Comment by jacksonliam** [comment]
Ok? What happens when you install libjpeg62-turbo-dev as it suggests?
