### ISSUE TITLE
How to find out supported resolutions?

### ISSUE THREAD

**Issue by ruvilonix** [jacksonliam/mjpg-streamer#374]
I have a USB cam and an OrangePi. The default resolution works, as does 1280x720, but I couldn't get other 16:9 resolutions (854x480, 640x360) to work. The log file says `The specified resolution is unavailable, using: width 640 height 480 instead`. How do I find out which resolutions are supported?

**Comment by poulou0** [comment]
I use `v4l2-ctl -d /dev/video0 --list-formats-ext` where, of course, `-d` is the path to your camera.
Hope it helps!

**Comment by ruvilonix** [comment]
@poulou0 Yep, that worked, thanks!
