### ISSUE TITLE
mjpeg-streamer not loading on boot

### ISSUE THREAD

**Issue by rojoricardo** [jacksonliam/mjpg-streamer#378]
I have Octopi installed and I i had the camera working but i wanted ti have custom controls in Octolapse, so it sugested to install your fork of mjpg-streamer-experimental, so i did, but now it seems mjpg-streamer is not starting on boot, and if I start it manualy, its basic resolution on the stream, how can I change it to start and manage the resolution with the /boot/octopi.txt ?

**Comment by jacksonliam** [comment]
Not the place for personal support requests,  please ask on a forum or Reddit or something.
