### ISSUE TITLE
Changing the default 8080 port for http output?

### ISSUE THREAD

**Issue by e4rthdog** [jacksonliam/mjpg-streamer#39]
Is there a possibility to change the 8080 port for the http output?

**Comment by jacksonliam** [comment]
In case anyone else finds this, see https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/output_http/README.md

**Comment by Whobeu** [comment]
Use -p on the command line. Example: -p 8888

Robert

**Comment by h00etn** [comment]
Sorry, I don't understand where I should put this command???

I'm trying to assign port 8085 instead of the 8080 to my stream (since I have another stream on 8080. So I put '-p 8085' where?
