### ISSUE TITLE
Trouble in PLUGIN_INPUT_RASPICAM

### ISSUE THREAD

**Issue by wzz618** [jacksonliam/mjpg-streamer#406]
I can't get input_raspicam from 'make' when l use raspberry pi os (64-bit):
`RB@RB:~/Desktop/mjpg-streamer/mjpg-streamer-experimental/_build $ uname -a
Linux RB 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux`
In debug mode, this trouble is shown in below:
`RB@RB:~/Desktop/mjpg-streamer/mjpg-streamer-experimental/_build $ cmake -DCMAKE_BUILD_TYPE=Release ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMAKE_BUILD_TYPE = Release
CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (Gphoto2).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  cmake/FindGphoto2.cmake:21 (include)
  plugins/input_ptp2/CMakeLists.txt:2 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (GPHOTO2)
  does not match the name of the calling package (Gphoto2).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindGphoto2.cmake:44 (find_package_handle_standard_args)
  plugins/input_ptp2/CMakeLists.txt:2 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The following features have been enabled:

 * PLUGIN_INPUT_FILE, File input plugin
 * PLUGIN_INPUT_HTTP, HTTP input proxy plugin
 * PLUGIN_INPUT_PTP2, PTP2 input plugin
 * PLUGIN_INPUT_UVC, Video 4 Linux input plugin
 * PLUGIN_OUTPUT_FILE, File output plugin
 * ENABLE_HTTP_MANAGEMENT, Enable experimental HTTP management option
 * PLUGIN_OUTPUT_HTTP, HTTP server output plugin
 * PLUGIN_OUTPUT_RTSP, RTSP output plugin
 * PLUGIN_OUTPUT_UDP, UDP output stream plugin
 * PLUGIN_OUTPUT_VIEWER, SDL output viewer plugin

-- The following OPTIONAL packages have been found:

 * OpenCV
 * Gphoto2
 * Threads
 * SDL

-- The following features have been disabled:

 * WXP_COMPAT, Enable compatibility with WebcamXP
 * PLUGIN_INPUT_OPENCV, OpenCV input plugin (unmet dependencies)
 * PLUGIN_INPUT_RASPICAM, Raspberry Pi input camera plugin (unmet dependencies)
 * PLUGIN_OUTPUT_ZMQSERVER, ZMQ Server output plugin (unmet dependencies)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/wzzRB/Desktop/mjpg-streamer/mjpg-streamer-experimental/_build`

**Comment by jacksonliam** [comment]
Input raspicam is only for the old camera API, you can either find the fork of this repo with an input_libcamera or use input_uvc.
