### ISSUE TITLE
syslog is overrun by mjpeg streamer info messages

### ISSUE THREAD

**Issue by ntoff** [jacksonliam/mjpg-streamer#54]
Trying to debug why my network is dropping out and 99% of all my syslogs are mjpeg streamer telling me it's serving localhost

>Dec 27 02:39:52 octoprint MJPG-streamer [476]: serving client: 127.0.0.1

Can we please not do this? A) I imagine it creates a tonne of writes to SD (or maybe not) and B) it makes going through the syslog looking for errors nearly impossible.

![image](https://cloud.githubusercontent.com/assets/9030085/21487771/c28829fe-cc1e-11e6-9319-20e3af31c2bc.png)

**Comment by jacksonliam** [comment]
Agreed this is stupid, fixed by https://github.com/jacksonliam/mjpg-streamer/commit/ac123fbbca16a46bd2d766ca774bf5ba581d9cb6
