### ISSUE TITLE
Streaming to stdout?

### ISSUE THREAD

**Issue by georgy7** [jacksonliam/mjpg-streamer#60]
Has it the option for streaming MJPEG binary data "as is" to the standard output?

    ./mjpg_streamer <SETTINGS> | myCustomEncrypterAndSender

**Comment by jacksonliam** [comment]
I do not believe so, no, as we output text to stdout. You should be able to use a named pipe and the file output plugin to achieve something similar.

**Comment by georgy7** [comment]
@jacksonliam Thanks for your response. I'll try it (for implementing some custom streaming protocol on another programming language). Also, I've just realized, it is much easier to use OpenVPN for encryption.
