### ISSUE TITLE
Please help me install this. 

### ISSUE THREAD

**Issue by paulpenney** [jacksonliam/mjpg-streamer#62]
Hello! Sorry but I am a PI NOOB. I will let you know my setup: 

I'm running Octoprint (3D Printer Software) that includes mjpg-streamer on it. I want the experimental version so I can access all the different features...

My main directory has an /mjpg-streamer folder in it with all the files from the original jpg-streamer release. Nested in that folder has an /mjpg-streamer-experimental folder in it that is empty. Can someone explain to me how I install this fork to my Pi?

Thanks!

Paul

**Comment by jacksonliam** [comment]
If you used octopi (to get octoprint) it has this version of mjpg-streamer on it already! 

General help requests are not an issue so am closing.
