### ISSUE TITLE
rotate and mirror

### ISSUE THREAD

**Issue by rubinlinux** [jacksonliam/mjpg-streamer#63]
It would be really handy to be able to rotate and/or mirror the image in the mjpg-streamer application so that one doesn't have to do so later down the line. Many raspberry pi mounting situations lead to upside-down cameras and the like.

**Comment by jacksonliam** [comment]
The rot function is supported by the input_raspicam plugin ` -rot : Set image rotation (0-359)`

The rotate and flip are supported by input_uvc plugin but may depend on the connected hardware/driver supporting it 
`[-rot ]................: Set image rotation (0-359)
[-hf ].................: Set horizontal flip (true/false)`
