### ISSUE TITLE
REQUEST: input_rtsp.so plugin request

### ISSUE THREAD

**Issue by NvrBst** [jacksonliam/mjpg-streamer#67]
Hello; I see there is a output_rtsp.so plugin. I was wondering how difficult would it be to give mjpg_streamer an RTSP (INPUT - input_rtsp.so) as a source. So that we can have it to convert an RTSP stream to an HTTP.

This would allow my OpenWRT router to take a RTSP IP Cam, can produce a webstream of it without the need for any other devices.

**Comment by jacksonliam** [comment]
Will accept a PR but not something I plan to work on personally (mainly due to lack of hardware and no personal use case)
