### ISSUE TITLE
domoticz 

### ISSUE THREAD

**Issue by Blacksly** [jacksonliam/mjpg-streamer#79]
Hi guys ! 

I have installed mjpg-streamer in my pi zero w with a camera pi and on another pi i have installed domoticz. 
Do you know how i can catch the video for create camera in domoticz ?? 

Thank you ! 

(sorry for my english) 
EDIT : 
I tried this configuration, dosen't work ....
![image](https://cloud.githubusercontent.com/assets/6670584/25034970/cff7e6c6-20ea-11e7-9422-bcdcedc03e2d.png)

**Comment by jacksonliam** [comment]
That looks OK (assuming you did start mjpg-streamer on port 9000).

Try one of these for the URL setting:
`/?action=snapshot`
`?action=snapshot`

**Comment by Blacksly** [comment]
Hey, thanks for your help ! 
Yes, mjpg is strating on port 9000
and i had try /?action=snapshot and ?action=snapshot, dosen't work too :/

**Comment by jacksonliam** [comment]
OK, and you can see the snapshot if you go to 192.168.1.17:9000/?action=snapshot in your browser?

**Comment by Blacksly** [comment]
Yep, I have the snapshot ^_^

**Comment by jacksonliam** [comment]
Then unfortunately I don't think I can help, sounds like mjpg-streamer is working fine, I'd go to domoticz for help. 
Perhaps they don't handle URLs without segments or with query parameters?

**Comment by Blacksly** [comment]
Okay, thanks for your help, I will go on Domoticz forum and I will try to reinstall Domoticz ^_^ thanks!
