### ISSUE TITLE
How to use -fourcc

### ISSUE THREAD

**Issue by gapx15** [jacksonliam/mjpg-streamer#81]
Hello

Can someone please tell me how to use -fourcc argument. Just example please.

I want to make it work with:
 v4l2-ctl --list-formats
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'S561' (compressed)
	Name        : S561

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'GBRG'
	Name        : GBRG

Thanks.

**Comment by jacksonliam** [comment]
It's `-fourcc RGBP`
