### ISSUE TITLE
output_http: is it possible to get the number of currently connected clients?

### ISSUE THREAD

**Issue by zpfvo** [jacksonliam/mjpg-streamer#84]
I'd like to know how many clients are connected at a given moment.
I enabled the `MANAGEMENT`-feature and now i can get a json with the connected clients and a timestamp of the latest received frame.
`GET http://localhost:8080/clients.json`
````.json

{
  "clients": [
    {
      "address": "127.0.0.1",
      "timestamp": 1496240473
    }
  ]
}
`````

Is it correct that every client that connects gets an entry in this JSON that will never expire? And if I wanted to check if any of those clients is still connected I need to check wether a timestamp is older than some seconds?

**Comment by jacksonliam** [comment]
I can't say I've used this feature, but I imagine it's a list of currently streaming clients and the last time they got a frame. 

Let me know if you find anything out!

Out of interest which method did you use to enable the `MANAGEMENT` define?

**Comment by zpfvo** [comment]
I compiled with CMake and used the line:
`cmake .. -DENABLE_HTTP_MANAGEMENT=ON`
