### ISSUE TITLE
an example to use output_rtsp please

### ISSUE THREAD

**Issue by romanten2017** [jacksonliam/mjpg-streamer#85]
Http is so nice.But I need to use rtsp for my project. 
Can you help me with some suggestion?
Thank so much.

**Comment by lzlcss** [comment]
also need an example, i use output_rtsp.so to run program, but cannot get stream in PC part via VLC

**Comment by romanten2017** [comment]
So do I.

**Comment by jacksonliam** [comment]
I think this is one of the more experimental plugins. I didn't write it and haven't used it. What do you want to use as the RTSP client? 

Here's the options, so it's just about specifying which port to listen on:
```
            " ---------------------------------------------------------------\n" \
            " The following parameters can be passed to this plugin:\n\n" \
            " [-p | --port ]..........: UDP port to listen for picture requests. UDP message is the filename to save\n\n" \
            " [-i | --input ].......: read frames from the specified input plugin (first input plugin between the arguments is the 0th)\n\n" \
            " ---------------------------------------------------------------\n");
```

**Comment by ighack** [comment]
mjpg_streamer -i "input_uvc.so -y" -o "output_rtsp.so -p 8081"
and I via VLC rtsp://pi_of_ip:8081.
I can't see anything
