### ISSUE TITLE
Add -rot to input_uvc.so

### ISSUE THREAD

**Issue by b-morgan** [jacksonliam/mjpg-streamer#88]
Please add -rot to input_uvc.so. Implementation can mirror the -rot implementation in input_raspi.so

**Comment by jacksonliam** [comment]
The rotate and flip are supported by input_uvc plugin but may depend on the connected hardware/driver supporting it
```
[-rot ]................: Set image rotation (0-359)
[-hf ].................: Set horizontal flip (true/false)
```

**Comment by dvv** [comment]
It can't be done in software by jtransform or manually, at least for the simplest cases such as 90 degree rotation?
TIA

**Comment by jacksonliam** [comment]
Probably can be done with libjepg, to avoid adding a new dependency, but it will be more cpu intensive. Feel free to do a PR add software rotation as an extra command line option.
