### ISSUE TITLE
very dark indoor image at 25fps

### ISSUE THREAD

**Issue by Serveurperso** [jacksonliam/mjpg-streamer#91]
The -iso parameter do not work, I tested -ev without success also.
How I can get the high gain (and noisy) video to make any indoor robotics use ?
I need >= 25FPS because lower framerate is useless for my project.

**Comment by Serveurperso** [comment]
You can test https://www.serveurperso.com/?page=robot original CCD camera from my robotic project
Versus http://www.serveurperso.com:8080/ raspicam version very dark:(

I made this launcher script :
```
(root|~/scripts) cat mjpg-streamer.sh
#!/bin/bash

pat=/root/mjpg-streamer/mjpg-streamer-experimental
bin=$pat/mjpg_streamer

i="input_raspicam.so -fps 25 -q 10 -x 720 -y 576 -rot 180"
o="output_http.so -p 8080"

LD_LIBRARY_PATH=$pat $bin -i "$i" -o "$o" -b
```

the -ex night do nothing also:(

**Comment by Serveurperso** [comment]
CCD Super HAD2 camera + complex analog video downlink :
![ccd](https://user-images.githubusercontent.com/4873680/30562921-6d1470cc-9cc0-11e7-95ec-537b1edcd439.png)

Raspicam :
![picam](https://user-images.githubusercontent.com/4873680/30562922-6e03fde0-9cc0-11e7-8f14-4fd65001db6f.png)

**Comment by jacksonliam** [comment]
Have you tried raspivid directly? Are you able to get a decent image out of that?

**Comment by Serveurperso** [comment]
No tested raspivid for now. Do you think the ISO param work with raspivid ?
I think it's the same limitation if you forward all parameter offered by raspivid ?

**Comment by jacksonliam** [comment]
If it doesn't work in raspivid there's not a lot I can do, but if it does then it's probably something I can fix, so it would be useful if you could try raspivid (with the same resolution/framerate) and let me know how it goes!

**Comment by Serveurperso** [comment]
hi, i tested

raspivid -fps 25 -w 720 -h 576 -ISO 800 -cd MJPEG -o /var/www/temp/video.mjpg

raspivid -fps 25 -w 720 -h 576 -mm average -ISO 800 -cd MJPEG -o /var/www/temp/video.mjpg

without success. always too dark...

**Comment by Serveurperso** [comment]
I tested all combination of exposure night/auto/off :
-ISO,  -ev and -mm are ignored

**Comment by Serveurperso** [comment]
I opened a issue on raspberry pi https://github.com/raspberrypi/userland/issues/424#issuecomment-330462594

**Comment by Serveurperso** [comment]
when I add the -drc high (dynamic range compensation to maximum) parameter the mjpeg streamer launch but there is no video stream...

**Comment by jacksonliam** [comment]
Looking at the other issue this appears to be a hardware problem so I'll close this for now, you might get more luck asking for tips on the raspberry pi forum on how to get the best low light video performance out of the sensor.
