### ISSUE TITLE
Issue with nginx (readv() failed (104: Connection reset by peer) while reading upstream)

### ISSUE THREAD

**Issue by Iambecomeroot** [jacksonliam/mjpg-streamer#95]
Sorry if this is the wrong place to put this but I am lost. I have googled the issue but I have only found unhelpful php stuff.

I am trying to proxy the webcam stream with nginx. My nginx config looks like this:
```
server {
  listen 443;

  ssl on;
  ...

  location /stream {
    proxy_pass http://127.0.0.1:8090?action=stream;
  }
}
```

When I restart nginx and try to view the webcam, I get the following error:
```
2017/10/19 12:51:23 [error] 861#861: *98 readv() failed (104: Connection reset by peer) while reading upstream, client: ***, server: ***, request: "GET /stream HTTP/1.1",      upstream: "http://127.0.0.1:8090?action=stream", host: "***"
```

I am running the mjpg_streamer with `sudo ./mjpg_streamer -i "./input_uvc.so" -o "./output_http.so -p 8090"`.

`uname -a`:
```
Linux nas 4.13.7-1-ARCH #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017 x86_64 GNU/Linux
```

**Comment by jacksonliam** [comment]
This looks like more of an nginx problem so I'd ask in that community. 

I'm not sure if you can pass query parameters like that with proxy_pass. 

Is this of help?
 https://github.com/foosel/OctoPrint/wiki/Reverse-proxy-configuration-examples

**Comment by Iambecomeroot** [comment]
Yes I needed to use `upstream`. Thank you very much. Sorry again for posting in the wrong spot.
