### ISSUE TITLE
EXIF data

### ISSUE THREAD

**Issue by agshift** [jacksonliam/mjpg-streamer#97]
I am able to run the stream (from usb2 webcam) as:
./mjpg_streamer -o "output_http.so -w ./www" -i "input_uvc.so -n -y -r 1920x1080 -q 100"

And also can take pictures using,
wget http://<raspPi local IP address>:8080/?action=snapshot -O output.jpg

But, I do not see the EXIF data for the image
When I run exiftool or ImageMagick's identify on "output.jpg", I don't see the EXIF tags. 

Is it possible to generate EXIF?
Thanks,
Amit

**Comment by jacksonliam** [comment]
I guess the way we are doing yuv to jpeg we are not adding exif flags.

It is an enhancement that could be made but not a priority for me, PRs welcome. 

You could also use a camera which supports JPEG output.
