### ISSUE TITLE
how to get quality 100% for mjpg

### ISSUE THREAD

**Issue by agshift** [jacksonliam/mjpg-streamer#99]
I am trying to use the MJPG format and also achieve 100% quality.
./mjpg_streamer -o "output_http.so -w ./www" -i "input_uvc.so -d /dev/video0 -n -r 2592x1944 -q 100"

But, when I check the image I see that the **quality has dropped to 64**. It somehow internally decided to drop the quality and I am unable to figure out why.
> jhead raspi_output_test.jpg
File name    : raspi_output_test.jpg
File size    : 134848 bytes
File date    : 2017:11:15 09:54:43
Resolution   : 2592 x 1944
**JPEG Quality : 64**

Is it possible to get 100% quality using MJPG format. With YUV I was able to.
Thanks,
Amit

**Comment by jacksonliam** [comment]
It's probably the best the camera can do. 
YUV mode does JPEG encoding using your CPU, JPEG mode does it in the camera.

Have you been able to get quality 100 with any other application? (e.g. v4l2-ctl)
